# Generated by Django 4.2.3 on 2023-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='percentage_completion',
            field=models.IntegerField(default=0),
        ),
    ]
