# Generated by Django 4.2.3 on 2023-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_percentage_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
